export const SET_MOVIES = 'SET_MOVIES';
export const SET_IS_LOADED = 'SET_IS_LOADED';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_CURRENT_MOVIE = 'SET_CURRENT_MOVIE';
export const SET_DELETE = 'SET_DELETE';
export const SEARCH_MOVIES_START = 'SEARCH_MOVIES_START';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE';
